LeeJongbokz/interviewPrep

build.gradle
src/main/java/com/example/interviewPrep/quiz/controller/MemberController.java
src/main/java/com/example/interviewPrep/quiz/domain/Member.java
src/main/java/com/example/interviewPrep/quiz/dto/MemberDTO.java
src/main/java/com/example/interviewPrep/quiz/repository/MemberRepository.java
src/main/java/com/example/interviewPrep/quiz/service/MemberService.java
src/main/java/com/example/interviewPrep/quiz/utils/PasswordCheck.java
src/main/java/com/example/interviewPrep/quiz/utils/ResponseEntityConstants.java
src/test/java/com/example/interviewPrep/quiz/Member/domain/MemberTest.java
src/test/java/com/example/interviewPrep/quiz/Member/dto/MemberDTOTest.java
src/test/java/com/example/interviewPrep/quiz/Member/repository/MemberRepositoryTest.java
src/test/java/com/example/interviewPrep/quiz/Member/service/MemberServiceTest.java

- 멤버 로그인을 위한  MemberController, MemberService, MemberRepository 클래스를 개발했습니다.
- 위의 세 클래스에 대한 테스트 코드를 개발했습니다.
- Util 클래스(ResponseEntityConstants, PasswordCheck)를 개발했습니다.

#8 멤버 로그인 Controller, Service, Repository 클래스, 테스트 코드, Util 클래스 개발

---

src/main/java/com/example/interviewPrep/quiz/controller/AnswerController.java
src/main/java/com/example/interviewPrep/quiz/domain/Answer.java
src/main/java/com/example/interviewPrep/quiz/domain/Question.java
src/main/java/com/example/interviewPrep/quiz/dto/AnswerDTO.java
src/main/java/com/example/interviewPrep/quiz/repository/AnswerRepository.java
src/main/java/com/example/interviewPrep/quiz/service/AnswerService.java
src/main/java/com/example/interviewPrep/quiz/utils/ResponseEntityConstants.java

- Answer 클래스 업데이트
-> Member 필드 추가
- AnswerController 클래스 업데이트
-> 클라이언트로부터 answers 받고 처리해서 AnswerService 클래스로 전달하는 로직 추가
- AnswerDTO, AnswerRepository 클래스 업데이트
- ResponseEntity 클래스에 RESPONSE_SERVER_ERROR 추가
- Question 클래스에 @Setter 추가

#10 Answer, AnswerController, AnswerDTO, AnswerRepository 클래스 업데이트

---

src/main/java/com/example/interviewPrep/quiz/dto/AnswersDTO.java

#11 AnswersDTO 클래스 추가

---

build.gradle
src/main/java/com/example/interviewPrep/quiz/controller/AnswerController.java
src/main/java/com/example/interviewPrep/quiz/controller/MemberController.java
src/main/java/com/example/interviewPrep/quiz/controller/QuestionController.java
src/main/java/com/example/interviewPrep/quiz/dto/AnswersDTO.java

- Restful URI 수정
- AnswersDTO 필드 수정
- 불필요한 공백 제거

#12 Restful URI 수정, AnswersDTO 필드 수정, 불필요한 공백 제거

---

src/main/java/com/example/interviewPrep/quiz/controller/QuestionController.java
src/main/java/com/example/interviewPrep/quiz/dto/AnswerDTO.java
src/main/java/com/example/interviewPrep/quiz/dto/AnswersDTO.java
src/main/java/com/example/interviewPrep/quiz/dto/MemberDTO.java
src/main/java/com/example/interviewPrep/quiz/dto/QuestionDTO.java
src/main/java/com/example/interviewPrep/quiz/service/MemberService.java
src/test/java/com/example/interviewPrep/quiz/Member/service/MemberServiceTest.java

- lombok 어노테이션 변경
- 메소드 접근제어자 변경
- Rollback(false) 제거

#13 lombok 어노테이션 변경, 메소드 접근제어자 변경(public->private), Rollback(false)제거

---

front/src/component/Login.js
front/src/component/Main.js
front/src/component/Test.js
front/src/component/TestScreen.js

- Test.js 파일을 수정했습니다.
- Login.js 파일을 수정했습니다.
- Main.js 파일을 수정했습니다.
- TestScreen.js 파일을 수정했습니다.

#14 Test, Login, Main, TestScreen 파일 수정

---

backend/src/main/java/com/example/interviewPrep/quiz/dto/AnswerDTO.java
backend/src/main/java/com/example/interviewPrep/quiz/dto/AnswersDTO.java
backend/src/main/java/com/example/interviewPrep/quiz/dto/MemberDTO.java
backend/src/main/java/com/example/interviewPrep/quiz/dto/QuestionDTO.java
backend/src/main/resources/application.yml

- DTO 클래스 버그 수정
- application.ytml 파일 버그 수정

#17 DTO 클래스 버그 수정, application.yml 파일 버그 수정

---

backend/build.gradle
backend/src/main/resources/application.yml

- mariadb 설정을 추가했습니다.
- 프로젝트 build 파일을 추가했습니다.

#18 mariadb 설정 추가, 프로젝트 build 파일 추가

---

backend/Dockerfile
backend/build.gradle
backend/build/resources/main/application.yml

- Docker를 이용한 배포를 하기 위해 Dockerfile을 추가했습니다
- build.gradle에 jar 관련 설정을 추가했습니다. 
- jar 파일을 새로 빌드해서 커밋했습니다.

#20 Dockerfile 추가, build.gradle 수정

---

backend/src/main/java/com/example/interviewPrep/quiz/controller/QuestionController.java
backend/src/main/java/com/example/interviewPrep/quiz/service/QuestionService.java

- List에서 Optional을 삭제했습니다.
-> List는 그 자체로 값이 없음을 표현할 수 있으므로,
Optional을 사용하면 중첩의 의미가 있으므로, 제거했습니다.
- for문을 forEach문으로 리팩토링

#22 List에서 Optional 삭제, for문-> forEach문 리팩토링 

---

backend/src/main/java/com/example/interviewPrep/quiz/repository/AnswerRepository.java
backend/src/main/java/com/example/interviewPrep/quiz/repository/MemberRepository.java
backend/src/main/java/com/example/interviewPrep/quiz/repository/QuestionRepository.java

- JPA 클래스를 삭제하고, Spring Data JPA 인터페이스를 추가했습니다.

#24 JPA 클래스를 삭제하고, Spring Data JPA 인터페이스를 추가

---

backend/src/main/java/com/example/interviewPrep/quiz/controller/AnswerController.java
backend/src/main/java/com/example/interviewPrep/quiz/repository/AnswerJpaRepository.java
backend/src/main/java/com/example/interviewPrep/quiz/service/AnswerService.java

- AnswerController에서 답안 생성 메소드를 복수-> 단수로 변경
- AnswerJpaRepository 클래스 삭제
- Answer 서비스 클래스 수정

#25 AnswerController에서 답안 생성 메소드를 복수-> 단수로 변경, AnswerJpaRepository 클래스 삭제, Answer 서비스 클래스 수정

---

backend/src/test/java/com/example/interviewPrep/quiz/Answer/controller/AnswerCreateWebControllerTest.java
backend/src/test/java/com/example/interviewPrep/quiz/Answer/repository/AnswerRepositoryTest.java

- AnswerCreateWebController 테스트
- AnswerRepository 테스트 수정

#27 AnswerCreateWebController 테스트, AnswerRepository 테스트 수정

---

backend/src/main/java/com/example/interviewPrep/quiz/controller/QuestionController.java
backend/src/main/java/com/example/interviewPrep/quiz/domain/Question.java
backend/src/main/java/com/example/interviewPrep/quiz/repository/QuestionRepository.java
backend/src/main/java/com/example/interviewPrep/quiz/service/QuestionService.java

- QuestionController 클래스 수정
- QuestionRepository 클래스 수정
- QuestionService 클래스 수정
- Question 클래스 수정

#28 QuestionController, QuestionRepository,QuestionService, Question 클래스 수정

---

backend/src/test/java/com/example/interviewPrep/quiz/Question/controller/QuestionCreateWebControllerTest.java
backend/src/test/java/com/example/interviewPrep/quiz/Question/controller/QuestionDeleteWebControllerTest.java
backend/src/test/java/com/example/interviewPrep/quiz/Question/controller/QuestionReadWebControllerTest.java
backend/src/test/java/com/example/interviewPrep/quiz/Question/controller/QuestionUpdateWebControllerTest.java
backend/src/test/java/com/example/interviewPrep/quiz/Question/repository/QuestionRepositoryTest.java
backend/src/test/java/com/example/interviewPrep/quiz/Question/service/QuestionServiceTest.java

#28-2 Question 관련 테스트 수정

---

backend/src/main/java/com/example/interviewPrep/quiz/dto/OAuthAttributes.java
backend/src/main/resources/application-oauth.yml

- 카카오 로그인 기능을 구현했습니다
- 네이버 로그인 기능을 구현했습니다.

#31 카카오 & 네이버 로그인 기능 구현

---

backend/src/main/resources/application.yml

#33 JPA 로그 출력 삭제

---

backend/src/main/java/com/example/interviewPrep/quiz/controller/QuestionController.java
backend/src/main/java/com/example/interviewPrep/quiz/domain/AnswerRepository.java
backend/src/main/java/com/example/interviewPrep/quiz/domain/MemberRepository.java
backend/src/main/java/com/example/interviewPrep/quiz/domain/QuestionRepository.java
backend/src/main/java/com/example/interviewPrep/quiz/infra/HeartRepository.java
backend/src/main/java/com/example/interviewPrep/quiz/infra/JpaAnswerRepository.java
backend/src/main/java/com/example/interviewPrep/quiz/infra/JpaMemberRepository.java
backend/src/main/java/com/example/interviewPrep/quiz/infra/JpaQuestionRepository.java
backend/src/main/java/com/example/interviewPrep/quiz/service/AnswerService.java
backend/src/main/java/com/example/interviewPrep/quiz/service/AuthenticationService.java
backend/src/main/java/com/example/interviewPrep/quiz/service/CustomOAuth2UserService.java
backend/src/main/java/com/example/interviewPrep/quiz/service/HeartService.java
backend/src/main/java/com/example/interviewPrep/quiz/service/MemberService.java
backend/src/main/java/com/example/interviewPrep/quiz/service/QuestionService.java
backend/src/test/java/com/example/interviewPrep/quiz/Answer/repository/AnswerRepositoryTest.java
backend/src/test/java/com/example/interviewPrep/quiz/Answer/service/AnswerServiceTest.java
backend/src/test/java/com/example/interviewPrep/quiz/Heart/repository/HeartRepositotyTest.java
backend/src/test/java/com/example/interviewPrep/quiz/Member/repository/MemberRepositoryTest.java
backend/src/test/java/com/example/interviewPrep/quiz/Member/service/AuthenticationServiceTest.java
backend/src/test/java/com/example/interviewPrep/quiz/Question/controller/QuestionCreateWebControllerTest.java
backend/src/test/java/com/example/interviewPrep/quiz/Question/controller/QuestionDeleteWebControllerTest.java
backend/src/test/java/com/example/interviewPrep/quiz/Question/controller/QuestionReadWebControllerTest.java
backend/src/test/java/com/example/interviewPrep/quiz/Question/controller/QuestionUpdateWebControllerTest.java
backend/src/test/java/com/example/interviewPrep/quiz/Question/repository/QuestionRepositoryTest.java
backend/src/test/java/com/example/interviewPrep/quiz/Question/service/QuestionServiceTest.java

- Repository 인터페이스를 추가하고, 
의존성 역전 원칙(DIP)을 적용하였습니다.

#34 Repository 인터페이스 추가, 의존성 역전 원칙 적용

---

backend/src/main/java/com/example/interviewPrep/quiz/errors/InvalidTokenException.java
backend/src/main/java/com/example/interviewPrep/quiz/utils/JwtUtil.java
backend/src/test/java/com/example/interviewPrep/quiz/utils/JwtUtilTest.java

- JWTUtil 클래스에 isTokenValid 메소드를 추가하고, decode 메소드를 수정했습니다.
- JWTUtil 테스트의 makeJWTtoken 메소드를 수정하고, decode시 예외 상황 테스트를 새로 추가했습니다.

#35 JWTUtil 클래스 isTokenValid 메소드 추가, JWTUtil 테스트 수정 및 추가

---

backend/src/main/java/com/example/interviewPrep/quiz/controller/MemberController.java

- 로그인 기능을 수정했습니다
1) 로그인 에러 시 로그를 출력할 수 있도록 수정했습니다
2) 예외 조건 검사를 추가했습니다
3) CORS 주소를 변경했습니다. 
4) @RestController의 주소를 수정했습니다.

#38 로그인 기능 수정

---

backend/src/main/java/com/example/interviewPrep/quiz/controller/MemberController.java
backend/src/main/java/com/example/interviewPrep/quiz/dto/SignUpRequestDTO.java
backend/src/main/java/com/example/interviewPrep/quiz/service/MemberService.java

#39 회원 가입 기능

---

backend/src/main/java/com/example/interviewPrep/quiz/controller/MemberController.java

- MemberController 클래스에서 
로그인 성공 시 HttpStatus.Unauthorized가 반환되던 것을
HttpStatus.OK가 반환되도록 수정했습니다.

#40 MemberController 클래스 에러 수정 

---

backend/src/main/java/com/example/interviewPrep/quiz/config/SecurityConfig.java

- 일반 로그인시 발생하는 CORS 이슈를 해결했습니다.

#44 일반 로그인 CORS 이슈 해결

---

backend/src/main/java/com/example/interviewPrep/quiz/controller/HeartController.java
backend/src/main/java/com/example/interviewPrep/quiz/domain/HeartRepository.java
backend/src/main/java/com/example/interviewPrep/quiz/infra/JpaHeartRepository.java
backend/src/main/java/com/example/interviewPrep/quiz/service/HeartService.java
backend/src/test/java/com/example/interviewPrep/quiz/Heart/domain/HeartTest.java
backend/src/test/java/com/example/interviewPrep/quiz/Heart/repository/HeartRepositotyTest.java
backend/src/test/java/com/example/interviewPrep/quiz/Heart/service/HeartServiceTest.java

#32 fix: Heart

---

backend/src/main/java/com/example/interviewPrep/quiz/exception/DuplicateEmailException.java
backend/src/main/java/com/example/interviewPrep/quiz/service/MemberService.java
backend/src/main/java/com/example/interviewPrep/quiz/utils/SHA256Util.java

- 일반 회원가입 시 이메일 중복 검사 및 비밀번호 암호화 기능을 추가하였습니다.

#47 일반 회원가입 시 이메일 중복 검사 및 비밀번호 암호화

---

backend/src/main/resources/application.yml

#51 redis yml 파일

---

backend/src/main/java/com/example/interviewPrep/quiz/controller/MemberController.java
backend/src/main/java/com/example/interviewPrep/quiz/service/MemberService.java

- MemberController의 어노테이션을 수정하고,
MemberService에 name을 생성하는 로직을 추가했습니다.

#52 MemberController 수정, MemberService 로직 추가

---

backend/src/main/java/com/example/interviewPrep/quiz/controller/MemberController.java
backend/src/test/java/com/example/interviewPrep/quiz/Member/controller/MemberControllerTest.java

- MemberController 수정하고, 
MemberController 테스트 추가했습니다.

#54 MemberController 수정, MemberController 테스트 추가

---

backend/src/main/java/com/example/interviewPrep/quiz/infra/JpaAnswerRepository.java
backend/src/main/java/com/example/interviewPrep/quiz/infra/JpaHeartRepository.java
backend/src/main/java/com/example/interviewPrep/quiz/infra/JpaMemberRepository.java
backend/src/main/java/com/example/interviewPrep/quiz/infra/JpaQuestionRepository.java

- JpaRepository import 문을 수정했습니다.

#56  JpaRepository import 문 수정

---

backend/build/resources/main/application.yml
backend/src/main/java/com/example/interviewPrep/quiz/controller/HeartController.java
backend/src/main/java/com/example/interviewPrep/quiz/domain/Answer.java
backend/src/test/java/com/example/interviewPrep/quiz/Heart/service/HeartServiceTest.java

- HeartController 클래스를 수정했습니다.
- HeartService 클래스를 수정했습니다.
- application.ytml 을 수정했습니다.
- Answer도메인을 수정했습니다.

#57-1 HeartContrller 수정, HeartService, application.yml, Answer 수정

---

backend/src/main/java/com/example/interviewPrep/quiz/service/AnswerService.java
backend/src/main/java/com/example/interviewPrep/quiz/service/AuthenticationService.java
backend/src/main/java/com/example/interviewPrep/quiz/service/CustomOAuth2UserService.java
backend/src/main/java/com/example/interviewPrep/quiz/service/QuestionService.java

- Service 클래스의 import문을 수정했습니다.

#58 Service 클래스 import문 수정

---

backend/src/test/java/com/example/interviewPrep/quiz/Answer/repository/AnswerRepositoryTest.java
backend/src/test/java/com/example/interviewPrep/quiz/Member/repository/MemberRepositoryTest.java
backend/src/test/java/com/example/interviewPrep/quiz/Member/service/AuthenticationServiceTest.java
backend/src/test/java/com/example/interviewPrep/quiz/Member/service/MemberServiceTest.java
backend/src/test/java/com/example/interviewPrep/quiz/Question/controller/QuestionCreateWebControllerTest.java
backend/src/test/java/com/example/interviewPrep/quiz/Question/controller/QuestionUpdateWebControllerTest.java
backend/src/test/java/com/example/interviewPrep/quiz/Question/repository/QuestionRepositoryTest.java
backend/src/test/java/com/example/interviewPrep/quiz/Question/service/QuestionServiceTest.java

#58-1 테스트 import문 수정

---

backend/src/test/java/com/example/interviewPrep/quiz/Question/controller/QuestionReadWebControllerTest.java

- QuestionReadWebController 테스트를 수정했습니다.

#58-2 QuestionReadWebController 테스트 수정

---

backend/src/main/java/com/example/interviewPrep/quiz/dto/AnswerDTO.java
backend/src/main/java/com/example/interviewPrep/quiz/dto/QuestionDTO.java

#59 DTO 어노테이션 수정

---

backend/src/main/java/com/example/interviewPrep/quiz/dto/SignUpRequestDTO.java
backend/src/main/java/com/example/interviewPrep/quiz/service/MemberService.java
backend/src/main/resources/application.yml

- Signup 과정에서 발생하는 버그를 수정했습니다.
(1) 전달된 SignUpRequestDTO 값으로 해당 객체가 생성되지 않았습니다.
-> SignUpRequestDTO의 애너테이션을 수정했습니다.
(2) 객체가 생성되었지만, insert 쿼리가 제대로 동작하지 않는 오류가 발생하였습니다.
->  application.yml에 h2 url에 MODE=LEGACY를 추가해서 해결했습니다.

#62 Signup 버그 수정

---

backend/src/main/java/com/example/interviewPrep/quiz/controller/HeartController.java
backend/src/main/java/com/example/interviewPrep/quiz/dto/AnswerDTO.java

- HeartController 클래스의 버그를 수정했습니다
1) HeartController의 인자값으로 @PathVariable 변수가 쓰이던 것을 @NotNull로 수정했습니다.
2) AnswerDTO 도메인의 어노테이션을 수정했습니다.

#64 Heartcontrller 클래스 버그 수정

---

backend/src/main/resources/application.yml

- application.yml을 수정해서 커밋했습니다.

#68 application.yml 파일 수정

---

backend/src/main/java/com/example/interviewPrep/quiz/repository/AnswerRepository.java
backend/src/main/java/com/example/interviewPrep/quiz/repository/HeartRepository.java
backend/src/main/java/com/example/interviewPrep/quiz/repository/MemberRepository.java
backend/src/main/java/com/example/interviewPrep/quiz/repository/QuestionRepository.java

repositorys -> repository 페키지로 경로 이동

#71 repository 경로 이동

---

backend/src/main/java/com/example/interviewPrep/quiz/controller/QuestionController.java
backend/src/main/java/com/example/interviewPrep/quiz/domain/Filter.java
backend/src/main/java/com/example/interviewPrep/quiz/dto/FilterDTO.java
backend/src/main/java/com/example/interviewPrep/quiz/infra/JpaAnswerRepository.java
backend/src/main/java/com/example/interviewPrep/quiz/infra/JpaFilterRepository.java
backend/src/main/java/com/example/interviewPrep/quiz/infra/JpaHeartRepository.java
backend/src/main/java/com/example/interviewPrep/quiz/infra/JpaMemberRepository.java
backend/src/main/java/com/example/interviewPrep/quiz/infra/JpaQuestionRepository.java
backend/src/main/java/com/example/interviewPrep/quiz/repository/FilterRepository.java
backend/src/main/java/com/example/interviewPrep/quiz/service/AnswerService.java
backend/src/main/java/com/example/interviewPrep/quiz/service/AuthenticationService.java
backend/src/main/java/com/example/interviewPrep/quiz/service/CustomOAuth2UserService.java
backend/src/main/java/com/example/interviewPrep/quiz/service/HeartService.java
backend/src/main/java/com/example/interviewPrep/quiz/service/MemberService.java
backend/src/test/java/com/example/interviewPrep/quiz/Answer/repository/AnswerRepositoryTest.java
backend/src/test/java/com/example/interviewPrep/quiz/Answer/service/AnswerServiceTest.java
backend/src/test/java/com/example/interviewPrep/quiz/Heart/service/HeartServiceTest.java
backend/src/test/java/com/example/interviewPrep/quiz/Member/repository/MemberRepositoryTest.java
backend/src/test/java/com/example/interviewPrep/quiz/Member/service/AuthenticationServiceTest.java
backend/src/test/java/com/example/interviewPrep/quiz/Question/controller/QuestionReadWebControllerTest.java
backend/src/test/java/com/example/interviewPrep/quiz/Question/repository/QuestionRepositoryTest.java
backend/src/test/java/com/example/interviewPrep/quiz/Question/service/QuestionServiceTest.java

controller
- question all(기본) 타입 조회
- filter 언어 리스트 조회
repository
- filter repository 추가
domain, dto
- filter 도메인, dto 추가
test 
- question filter 언어 리스트 조회 테스트 작성

#73 Question 기본 타입 조회, 필터 언어 리스트 조회

---

backend/src/main/java/com/example/interviewPrep/quiz/service/QuestionService.java

[기본 조회 기능(type=all)]
- question service 파일 추가

#73-2 question service 기본 조회 기능

---

frontend/package.json
frontend/src/App.js
frontend/src/component/Login.js
frontend/src/component/MyPage/Profile.js
frontend/src/component/Problem.js
frontend/src/component/ProblemList.js
frontend/src/component/Select.js
frontend/src/component/SignUp.js
frontend/src/component/Test.js
frontend/src/component/UI/PaperUI.js
frontend/src/index.js
frontend/src/layout/Header.js
frontend/src/pages/AnswerListPage.js
frontend/src/pages/MyPage.js
frontend/src/pages/TestScreenPage.js
frontend/src/store/auth-context.js

대응 한 기능 
- 로그인/로그아웃 ( 쿠키 적용 )
- 로그인, 회원가입 폼 수정

frontend 11월 2주차 주말

---

frontend/src/component/Problem.js
frontend/src/component/ProblemList.js
frontend/src/component/Select.js
frontend/src/component/SignUp.js
frontend/src/component/Test.js
frontend/src/layout/Header.js

[frontend] 11월 3주차 평일

---

backend/src/main/java/com/example/interviewPrep/quiz/controller/AnswerController.java
backend/src/main/java/com/example/interviewPrep/quiz/controller/QuestionController.java
backend/src/main/java/com/example/interviewPrep/quiz/exception/advice/CommonControllerAdvice.java
backend/src/main/java/com/example/interviewPrep/quiz/service/AnswerService.java
backend/src/main/java/com/example/interviewPrep/quiz/service/QuestionService.java
backend/src/main/java/com/example/interviewPrep/quiz/utils/Result.java

[custom responseEntity, RestControllerAdvice 적용]
- responseEntity body custom 하여 Result.java 파일 생성
- question, answer controller에 적용 -> 모든 응답 ok(200)으로 통신
- RestcontrollerAdvice AOP 적용하여 예외 발생시 응답은 ok(200)이지만 body 안에 code는 "800"으로 처리

#77 custom responseEntity, controllerAdvice 적용

---

backend/src/main/java/com/example/interviewPrep/quiz/exam/controller/ExamController.java
backend/src/main/java/com/example/interviewPrep/quiz/exam/service/ExamService.java
backend/src/main/java/com/example/interviewPrep/quiz/exception/advice/ErrorCode.java

- 모의고사 컨트롤러에서 커스텀리스폰스(resultResponse) 사용

refact: 커스텀 response 리팩토링

---

backend/src/main/java/com/example/interviewPrep/quiz/answer/domain/Answer.java
backend/src/main/java/com/example/interviewPrep/quiz/answer/service/AnswerService.java
backend/src/main/java/com/example/interviewPrep/quiz/config/SecurityConfig.java
backend/src/main/java/com/example/interviewPrep/quiz/member/controller/MemberController.java
backend/src/main/java/com/example/interviewPrep/quiz/member/domain/Member.java
backend/src/main/java/com/example/interviewPrep/quiz/member/service/AuthenticationService.java
backend/src/main/java/com/example/interviewPrep/quiz/member/service/MemberService.java
backend/src/main/java/com/example/interviewPrep/quiz/utils/JwtUtil.java
backend/src/main/resources/application.yml
backend/src/test/java/com/example/interviewPrep/quiz/Member/service/AuthenticationServiceTest.java

1) MemberController에 Custom Response인 ResultResponse를 반영하여 리팩토링을 진행하였습니다.
2) JwtUtil에 getMemberId라는 static 메소드를 추가하고, AnswerService의 createAnswer 메소드에서 호출하는 식으로 
로그인 체크를 하도록 수정했습니다.

#87 AnswerService, Member 관련 클래스 리팩토링

---

backend/src/main/java/com/example/interviewPrep/quiz/exam/domain/Exam.java
backend/src/main/java/com/example/interviewPrep/quiz/heart/domain/Heart.java

1) Heart 클래스, Exam 클래스의 GenerationStrategy를 IDENTITY로 수정했습니다.

#88 Domain 클래스 GenerationStrategy 수정

---

backend/src/main/java/com/example/interviewPrep/quiz/config/SecurityConfig.java
backend/src/main/java/com/example/interviewPrep/quiz/exception/advice/ErrorCode.java
backend/src/main/java/com/example/interviewPrep/quiz/member/controller/MemberController.java
backend/src/main/java/com/example/interviewPrep/quiz/utils/JwtUtil.java

1) 스프링 시큐리티의 로그아웃 기능을 추가했습니다. 
2) getMemberId 메소드에 대한 Exception을 적용했습니다.

#89 로그아웃 기능 추가

---

backend/src/main/java/com/example/interviewPrep/quiz/filter/JwtAuthenticationFilter.java

#91 JWT 필터 추가

---

frontend/src/App.js
frontend/src/component/Exam/ExamList.js
frontend/src/component/Exam/FrontendExam.js
frontend/src/component/MyPage/Profile.js
frontend/src/layout/Header.js
frontend/src/pages/FrontendExamPage.js

- 모의고사 ui수정 및 api 연동
- 메인페이지 회원정보 수정 api 반영
- 카테고리 클릭 시 강조 표시

11월 5주차 평일

---

backend/src/main/java/com/example/interviewPrep/quiz/answer/controller/CommentController.java
backend/src/main/java/com/example/interviewPrep/quiz/answer/domain/AnswerComment.java
backend/src/main/java/com/example/interviewPrep/quiz/answer/dto/req/CommentReq.java
backend/src/main/java/com/example/interviewPrep/quiz/answer/dto/res/CommentRes.java
backend/src/main/java/com/example/interviewPrep/quiz/answer/repository/CommentRepository.java
backend/src/main/java/com/example/interviewPrep/quiz/answer/service/CommentService.java
backend/src/main/java/com/example/interviewPrep/quiz/utils/DateFormat.java

[댓글 기능 추가]
- 댓글 작성, 수정, 삭제
- 댓글 리스트 조회

#90 댓글 기능 추가

---

backend/src/main/java/com/example/interviewPrep/quiz/exception/advice/ErrorCode.java
backend/src/main/java/com/example/interviewPrep/quiz/member/controller/MemberController.java
backend/src/main/java/com/example/interviewPrep/quiz/member/repository/MemberRepository.java
backend/src/main/java/com/example/interviewPrep/quiz/member/service/MemberService.java

- 마이 페이지 기본 정보 로딩 기능을 추가했습니다. 
- 이메일, 닉네임 변경을 하나의 버튼으로 할 수 있게 추가하였으며,
이에 대한 중복 검사 기능도 추가하였습니다.

#91 마이페이지 기본 정보 로딩, 이메일, 닉네임 변경 추가

---

backend/build.gradle
backend/src/main/java/com/example/interviewPrep/quiz/config/Swagger2Config.java

http://localhost:8080/swagger-ui.html

#95 [feat] Swagger 설치

---

backend/src/main/java/com/example/interviewPrep/quiz/answer/domain/Answer.java
backend/src/main/java/com/example/interviewPrep/quiz/exception/advice/ErrorCode.java
backend/src/main/java/com/example/interviewPrep/quiz/heart/controller/HeartController.java
backend/src/main/java/com/example/interviewPrep/quiz/heart/dto/HeartRequestDTO.java
backend/src/main/java/com/example/interviewPrep/quiz/heart/service/HeartService.java

- 'POST' /heart (request body "answerId")
- 'DELETE' /heart (request body "answerId")
일단 구현에 집중했습니다.
포스트맨 작동 확인 
테스트 코드와 Optimistic Lock은 추후 리팩토링을 통해 구현하겠습니다.

#96 [Refact] 좋아요 멤버확인 & OptimisticLock 구현

---

backend/build.gradle
backend/src/main/java/com/example/interviewPrep/quiz/config/EmailConfig.java
backend/src/main/java/com/example/interviewPrep/quiz/email/controller/EmailController.java
backend/src/main/java/com/example/interviewPrep/quiz/email/service/EmailService.java
backend/src/main/java/com/example/interviewPrep/quiz/email/service/EmailServiceImpl.java
backend/src/main/resources/email.properties

- 이메일 변경 시 확인용으로 발송하는 메일 기능을 개발했습니다.

#97 이메일 변경 확인 메일 기능

---

backend/src/main/java/com/example/interviewPrep/quiz/answer/dto/SolutionDTO.java
backend/src/main/java/com/example/interviewPrep/quiz/answer/dto/res/CommentRes.java
backend/src/main/java/com/example/interviewPrep/quiz/answer/repository/AnswerRepository.java
backend/src/main/java/com/example/interviewPrep/quiz/answer/repository/CommentRepository.java
backend/src/main/java/com/example/interviewPrep/quiz/answer/service/AnswerService.java
backend/src/main/java/com/example/interviewPrep/quiz/answer/service/CommentService.java
backend/src/main/java/com/example/interviewPrep/quiz/exception/advice/ErrorCode.java
backend/src/main/java/com/example/interviewPrep/quiz/question/controller/ReferenceController.java
backend/src/main/java/com/example/interviewPrep/quiz/question/domain/QuestionReference.java
backend/src/main/java/com/example/interviewPrep/quiz/question/dto/ReferenceDTO.java
backend/src/main/java/com/example/interviewPrep/quiz/question/repository/ReferenceRepository.java
backend/src/main/java/com/example/interviewPrep/quiz/question/service/ReferenceService.java

[reference 기능 추가]
-ref 작성, 수정, 삭제, 목록 조회 기능 추가
[dto 날짜 추가-답안, 댓글, 참조 ]
-생성, 수정, 수정 여부 값 추가
-service, rep 수정
[같은 questionId 답안 조회 오류 수정]
-rep, service 수정

#98 reference 기능 추가, 날짜 추가(answer, comment, ref), 답안 보기 오류 수정

---

backend/src/main/java/com/example/interviewPrep/quiz/exam/controller/ExamController.java
backend/src/main/java/com/example/interviewPrep/quiz/exam/domain/Exam.java
backend/src/main/java/com/example/interviewPrep/quiz/exam/service/ExamService.java

[fix] 모의고사 제출시 에러 해결

---

backend/src/main/java/com/example/interviewPrep/quiz/exam/domain/Exam.java
backend/src/main/java/com/example/interviewPrep/quiz/exam/service/ExamService.java

- examId 컬럼명 삭제
- answer 객체 생성

[fix] 모의고사 제출 오류 해결

---

backend/.gitignore
backend/src/main/java/com/example/interviewPrep/quiz/answer/controller/CommentController.java
backend/src/main/java/com/example/interviewPrep/quiz/answer/domain/Answer.java
backend/src/main/java/com/example/interviewPrep/quiz/answer/dto/SolutionDTO.java
backend/src/main/java/com/example/interviewPrep/quiz/answer/service/AnswerService.java
backend/src/main/java/com/example/interviewPrep/quiz/answer/service/CommentService.java
backend/src/main/java/com/example/interviewPrep/quiz/dto/CreateDto.java
backend/src/main/java/com/example/interviewPrep/quiz/question/controller/ReferenceController.java
backend/src/main/java/com/example/interviewPrep/quiz/question/dto/ReferenceDTO.java
backend/src/main/java/com/example/interviewPrep/quiz/question/service/ReferenceService.java

[reference]
본인이 쓴 ref인지 구분하는 필드 추가

#100 reference 본인이 쓴건지 구분 추가, 댓글 cnt, create 작업 후 id 반환

---

backend/src/main/java/com/example/interviewPrep/quiz/exam/controller/ExamController.java
backend/src/main/java/com/example/interviewPrep/quiz/exam/domain/ExamKit.java
backend/src/main/java/com/example/interviewPrep/quiz/exam/dto/ExamKitListRes.java
backend/src/main/java/com/example/interviewPrep/quiz/exam/dto/ExamKitReq.java
backend/src/main/java/com/example/interviewPrep/quiz/exam/dto/ExamKitRes.java
backend/src/main/java/com/example/interviewPrep/quiz/exam/dto/ExamkitRes.java
backend/src/main/java/com/example/interviewPrep/quiz/exam/dto/MyExamRes.java
backend/src/main/java/com/example/interviewPrep/quiz/exam/service/ExamService.java

1. 모의고사키트 목록 불러오기에서 Question들을 Response값으로 보이던것을 수정
2. 내가 푼 모의고사에서 Question title이 안불러와 지는 것을 수정

#101 [Fix] 모의고사 기능 수정

---

backend/src/main/java/com/example/interviewPrep/quiz/exception/advice/CommonControllerAdvice.java
backend/src/main/java/com/example/interviewPrep/quiz/member/controller/MemberController.java
backend/src/main/java/com/example/interviewPrep/quiz/member/dto/SignUpRequestDTO.java

form valid 값 검사
- dto 수정
- invalid한 값 controllerAdvice 예외 적용

#101 회원가입 값 vaild 검사, invalid controllerAdvice 예외 적용

---

backend/src/main/java/com/example/interviewPrep/quiz/answer/controller/CommentController.java
backend/src/main/java/com/example/interviewPrep/quiz/answer/service/AnswerService.java
backend/src/main/java/com/example/interviewPrep/quiz/answer/service/CommentService.java
backend/src/main/java/com/example/interviewPrep/quiz/dto/CreateDto.java
backend/src/main/java/com/example/interviewPrep/quiz/question/service/ReferenceService.java

- comment 두 번 저장 오류 수정
- 이름, 날짜 추가(answer, comment, ref)

#102 comment 두 번 작성 오류, 이름, 날짜 추가(answer, comment, ref)

---

backend/src/main/java/com/example/interviewPrep/quiz/heart/controller/RefHeartController.java
backend/src/main/java/com/example/interviewPrep/quiz/heart/domain/RefHeart.java
backend/src/main/java/com/example/interviewPrep/quiz/heart/repository/RefHeartRepository.java
backend/src/main/java/com/example/interviewPrep/quiz/heart/service/RefHeartService.java
backend/src/main/java/com/example/interviewPrep/quiz/question/service/ReferenceService.java

- /ref-heart/{id}
POST: 좋아요 등록
DELETE: 좋아요 삭제
- /question/ref/{id}
GET: cntHeart 조회 가능

#103 Feat reference 좋아요 구현

---

backend/src/main/java/com/example/interviewPrep/quiz/filter/JwtAuthenticationFilter.java
backend/src/main/java/com/example/interviewPrep/quiz/member/controller/MemberController.java

[memberController, filter]
package 경로 추가

#106 memberController, filter import 추가

---

backend/src/main/java/com/example/interviewPrep/quiz/config/CustomAuthenticationEntryPoint.java
backend/src/main/java/com/example/interviewPrep/quiz/exception/advice/LoginControllerAdvice.java
backend/src/main/java/com/example/interviewPrep/quiz/exception/advice/LoginException.java
backend/src/main/java/com/example/interviewPrep/quiz/filter/JwtAuthenticationFilter.java
backend/src/main/java/com/example/interviewPrep/quiz/member/controller/MemberController.java
backend/src/main/java/com/example/interviewPrep/quiz/member/service/AuthenticationService.java

[login]
login 실패시 401 status로 응답하는 controllerAdvice 추가
[token]
토큰 만료 시 cookie null일 때 오류 수정

#107 login exception 추가, token reissue 오류 수정

---

backend/src/main/java/com/example/interviewPrep/quiz/member/social/service/OauthService.java

[oauth]
인증 객체 생성 시 유저 id 타입 오류 수정

#110 Oauth login 오류 수정

---

backend/src/main/java/com/example/interviewPrep/quiz/answer/domain/Answer.java
backend/src/main/java/com/example/interviewPrep/quiz/answer/service/AnswerService.java

1) Answer 도메인
-> question_title을 추가했습니다
2) AnswerService 클래스
-> Answer 객체를 생성할 때, question_title을 추가했습니다.

#111 Answer 도메인, AnswerService 클래스 수정

---

backend/src/main/java/com/example/interviewPrep/quiz/email/controller/EmailController.java
backend/src/main/java/com/example/interviewPrep/quiz/email/service/EmailService.java
backend/src/main/java/com/example/interviewPrep/quiz/email/service/EmailServiceImpl.java

1) 회원가입 시 Email 인증 하는 기능을 추가하였습니다.

#112 회원가입 시 Email 인증 기능 추가

---

backend/src/main/java/com/example/interviewPrep/quiz/member/controller/MemberController.java
backend/src/main/java/com/example/interviewPrep/quiz/member/domain/Member.java
backend/src/main/java/com/example/interviewPrep/quiz/member/service/MemberService.java

1) Member 도메인
-> answers 리스트에 대한 순환 참조 문제 해결
2) MemberService 클래스
-> AccessToken에 저장된 memberId를 가져오는 JwtUtil.getMemberId() 추가
3) MemberController 클래스
-> @Valid 어노테이션 제거

#113 Member 도메인, MemberService, MemberController 클래스 수정

---

backend/src/main/java/com/example/interviewPrep/quiz/question/domain/Question.java

1)  List<ExamKitQuestion> questions 주석 처리
-> Exam 기능을 잠정적으로 중단하여서, 주석 처리 하였습니다

#113 List<ExamKitQuestion> questions 주석 처리

---

backend/src/main/java/com/example/interviewPrep/quiz/exam/controller/ExamController.java
backend/src/main/java/com/example/interviewPrep/quiz/exam/domain/Exam.java
backend/src/main/java/com/example/interviewPrep/quiz/exam/domain/ExamAnswer.java
backend/src/main/java/com/example/interviewPrep/quiz/exam/domain/ExamKit.java
backend/src/main/java/com/example/interviewPrep/quiz/exam/domain/ExamKitQuestion.java
backend/src/main/java/com/example/interviewPrep/quiz/exam/dto/ExamKitListRes.java
backend/src/main/java/com/example/interviewPrep/quiz/exam/dto/ExamKitReq.java
backend/src/main/java/com/example/interviewPrep/quiz/exam/dto/ExamRes.java
backend/src/main/java/com/example/interviewPrep/quiz/exam/dto/ExamkitRes.java
backend/src/main/java/com/example/interviewPrep/quiz/exam/dto/MyExamRes.java
backend/src/main/java/com/example/interviewPrep/quiz/exam/repository/ExamAnswerRepository.java
backend/src/main/java/com/example/interviewPrep/quiz/exam/repository/ExamKitQuestionRepository.java
backend/src/main/java/com/example/interviewPrep/quiz/exam/repository/ExamKitRepository.java
backend/src/main/java/com/example/interviewPrep/quiz/exam/repository/ExamRepository.java
backend/src/main/java/com/example/interviewPrep/quiz/exam/service/ExamService.java

#115 Exam 기능 주석 처리

---

backend/src/main/java/com/example/interviewPrep/quiz/filter/JwtAuthenticationFilter.java
backend/src/main/java/com/example/interviewPrep/quiz/member/service/AuthenticationService.java

#116 accessToken 버그 수정

---

backend/build.gradle

#117 swagger 패키지 주석 처리

---

backend/src/main/java/com/example/interviewPrep/quiz/email/service/EmailServiceImpl.java
backend/src/main/java/com/example/interviewPrep/quiz/member/controller/MemberController.java
backend/src/main/java/com/example/interviewPrep/quiz/member/domain/Member.java
backend/src/main/java/com/example/interviewPrep/quiz/member/dto/SignUpRequestDTO.java
backend/src/main/java/com/example/interviewPrep/quiz/member/service/MemberService.java
backend/src/main/java/com/example/interviewPrep/quiz/utils/AES256.java

- 회원가입 시 회사 이메일로 인증하는 기능을 추가했습니다.

#118 회원가입 시 회사 이메일 인증 기능 추가

---

src/main/java/com/example/interviewPrep/quiz/question/controller/QuestionController.java
src/main/java/com/example/interviewPrep/quiz/question/service/QuestionService.java

- Question Size를 반환하는 기능을 추가했습니다.

#121 Question Size 반환 기능 추가

---

src/main/java/com/example/interviewPrep/quiz/answer/domain/Answer.java
src/main/java/com/example/interviewPrep/quiz/answer/service/AnswerService.java

- Answer 도메인에서 question_title을 삭제했습니다 .

#122 Answer 도메인에서 question_title 삭제

---

src/main/java/com/example/interviewPrep/quiz/email/service/EmailServiceImpl.java

- emailVerifyUrl을 localhost:3000에서 interviewprep.kr로 수정했습니다. 
- System.out.println 제거했습니다.

#123 emailVerifyUrl 수정, System.out.println 제거
